version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: lic_db
      POSTGRES_USER: lic_user
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    container_name: redis_broker
    restart: always
    ports:
      - "6379:6379"
  
  app:
    build: .
    container_name: fastapi_scrapper_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://lic_user:123456789@postgres_db:5432/lic_db"
      REDIS_URL: "redis://redis_brocker:6379/0"
  
  celery_worker:
    build: .
    container_name: celery_worker
    restart: always
    depends_on:
      - redis
      - app
    environment:
      DATABASE_URL: "postgresql://lic_user:123456789@postgres_db:5432/lic_db"
      REDIS_URL: "redis://redis_brocker:6379/0"
    command: ["sh","run_celery.sh"]
    
      
volumes:
  pgdata:
