version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: lic_db
      POSTGRES_USER: lic_user
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    container_name: redis_broker
    restart: always
    ports:
      - "6379:6379"
      
volumes:
  pgdata:
